apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello-service
  namespace: default
spec:
  ports:
    - nodePort: 30808
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello
    version: v1
  sessionAffinity: None
  type: NodePort
